[package]
name = "regal_native"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "regal_native"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
bmp = "0.5"
jpeg-decoder = "0.1.20"
lazy_static = "1.0"
png = "0.16"
regex = "1.4"
rustler = "0.21.1"
tiff = "0.6"
